# Generated by Django 5.2.6 on 2025-09-25 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produit",
            old_name="quantité",
            new_name="quantite",
        ),
    ]
