# Generated by Django 5.2.6 on 2025-09-25 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0002_rename_quantité_produit_quantite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fabrication",
            old_name="utilisations_matiere_premiere",
            new_name="utilisation_matiere_premiere",
        ),
    ]
